apps/dashboard/urls.py
from django.conf.urls import patterns, url
from .views import dashboard

urlpatterns = patterns(
    '',
    url(
        r'^$', dashboard, name='dashboard'),
)

grpanel/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from plugins.base.utils import init_plugins, update_plugins_urls


init_plugins()


urlpatterns = patterns(
    '',
    url(r'^', include('apps.accounts.urls')),
    url(r'^', include('apps.dashboard.urls')),
    url(r'^hosts/', include('apps.hosts.urls')),
    url(r'^applications/', include('apps.applications.urls')),
    url(r'^sshkeys/', include('apps.sshkeys.urls')),
    url(r'^plugins/', include('plugins.base.urls')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url('^robots\.txt$', TemplateView.as_view(
        template_name='robots.txt', content_type='text/plain')),
    url('^humans\.txt$', TemplateView.as_view(
        template_name='humans.txt', content_type='text/plain')),
)

# Load plugins urls
urlpatterns = update_plugins_urls(urlpatterns)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns += patterns(
        '',
        url('^demo-email\.html$', TemplateView.as_view(
            template_name='email/base.html')),
        url('^demo-email\.txt$', TemplateView.as_view(
            template_name='email/base.txt', content_type='text/plain')),
    )

    urlpatterns = patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',  # NOQA
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ) + staticfiles_urlpatterns() + urlpatterns  # NOQA

    import debug_toolbar
    urlpatterns += patterns(
        '',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

plugins/backups/models.py
import psycopg2
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.utils.crypto import get_random_string
from apps.passwords.mixins import ModelWithPassword
from apps.applications.models import WebApplication


def get_backup_passphrase():
    return get_random_string(
        50, "abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)")


class BackupSettings(ModelWithPassword):
    BACKUP_SCHEDULE_CHOICES = (
        ('never', _('Never')),
        ('daily', _('Daily')),
        ('weekly', _('Weekly')),
    )
    MAX_AGE_CHOICES = (
        ('1W', _('1 Week')),
        ('2W', _('2 Weeks')),
        ('3W', _('3 Weeks')),
        ('1M', _('1 Month')),
        ('2M', _('2 Months')),
        ('3M', _('3 Months')),
        ('6M', _('6 Months')),
        ('1Y', _('1 Year')),
        ('2Y', _('2 Years')),
    )

    webapp = models.OneToOneField(
        WebApplication,
        verbose_name=_('Web application'),
        related_name='backup_settings')
    passphrase = models.CharField(
        _('Encription passphrase'),
        max_length=100,
        default=get_backup_passphrase,
        help_text=_(
            'All your backups will be encripted with this passphrase.'))
    target = models.CharField(
        _('Target'),
        max_length=255,
        default=
        's3://s3-<region endpoint name>.amazonaws.com/'
        '<bucket name>/<folder name>',
        help_text=_('Specify where you want to store your backups.'))
    username = models.CharField(_('Target user'), max_length=100)

    max_age = models.CharField(
        _('Max age'), max_length=20, default='2M',
        choices=MAX_AGE_CHOICES,
        help_text=_('Time frame for old backups to keep.'))
    volsize = models.IntegerField(
        _('Volume size'), default=25,
        help_text=_('Volume size in MB'))

    max_full_backups = models.IntegerField(
        _('Max full backups'), default=4,
        help_text=_('Number of full backups to keep.'))
    max_full_backup_age = models.CharField(
        _('Max full backup age'), max_length=20, default='1M',
        choices=MAX_AGE_CHOICES,
        help_text=_(
            'Forces a full backup if last full backup '
            'reaches a specified age.'))
    s3_european_bucket = models.BooleanField(
        _('S3 european bucket'), default=True, blank=True,
    )
    s3_use_new_style = models.BooleanField(
        _('S3 new style auth'), default=True, blank=True,
    )

    duply_status = models.TextField(
        _('Duply status'), blank=True, default='')
    last_update = models.DateTimeField(_('Last update'), auto_now=True)

    schedule = models.CharField(
        _('Schedule'), default='never', max_length=50,
        choices=BACKUP_SCHEDULE_CHOICES)

    class Meta:
        verbose_name = _('Backup settings')
        verbose_name_plural = _('Backup settings')

    def __str__(self):
        return str(self.webapp)

    def get_duply_config_file_name(self, filename='conf'):
        import os
        return os.path.join(
            '/home',
            self.webapp.host.main_user,
            '.duply',
            self.webapp.name,
            filename)

    def get_extra_backup_directory(self):
        import os
        return os.path.join(
            '/home',
            self.webapp.host.main_user,
            'backups',
            self.webapp.name)

    def get_creation_cmd(self):
        return 'sudo duply %s create' % self.webapp.name

    def get_status_cmd(self):
        return 'sudo duply %s status' % self.webapp.name

    def get_backup_cmd(self):
        return 'sudo duply %s backup' % self.webapp.name

    def get_restore_to_dir_cmd(self):
        import os
        return 'sudo duply %s restore %s' % (
            self.webapp.name,
            os.path.join(
                '/home',
                self.webapp.host.main_user,
                'tmp',
                self.webapp.name),
        )

    def update_status(self):
        self.duply_status = self.backup_status_cmd()
        self.save()

    def backup_status_cmd(self):
        from apps.hosts.utils import exec_cmd_on_host
        result = exec_cmd_on_host(
            self.webapp.host_id,
            self.get_status_cmd(),
            sudo=True)
        result = '\n'.join(str(result[0], 'utf-8').splitlines()[2:])
        return result

    def start_backup_cmd(self):
        from apps.hosts.utils import exec_cmd_on_host
        result = exec_cmd_on_host(
            self.webapp.host_id,
            self.get_backup_cmd(),
            sudo=True)
        result = '\n'.join(str(result[0], 'utf-8').splitlines()[2:])
        return result

    def get_backup_status_as_obj(self):
        import re
        _result = {}

        # Get last status check time
        w = re.search(
            r'--- Start running command STATUS at (?P<time>.+) ---',
            self.duply_status,
        )
        _result['last_status_check'] = w.groups() if w else ''

        # Metadata sync status
        w = re.search(
            r'Local and Remote metadata are synchronized, no sync needed.',
            self.duply_status,
        )
        _result['matadata_are_synchronized'] = bool(w)

        # Last full backup date
        w = re.search(
            r'Last full backup date: (?P<date>.+)'+'\n',
            self.duply_status,
        )
        _result['last_full_backup'] = w.groups() if w else ''

        # Backup sets
        w = re.search(
            r'Number of contained backup sets: (?P<num>\d+)'+'\n',
            self.duply_status,
        )
        _result['backup_sets_count'] = int(w.groups()[0]) if w else 0
        _result['backup_sets'] = []
        _lines = self.duply_status.splitlines()
        _table_start = -1
        for (i, s) in enumerate(_lines):
            if s.startswith(' Type of backup set:'):
                _table_start = i
                break
        for i in range(_table_start+1, len(_lines)):
            if _lines[i].startswith('-------------------------'):
                break
            else:
                _decoded_bset = list(
                    map(
                        lambda x: x.strip(),
                        filter(bool, _lines[i].split('  '))
                    )
                )
                _result['backup_sets'].append(_decoded_bset)

        return _result

    def get_duply_config(self):
        from apps.hosts.utils import read_file
        filename = self.get_duply_config_file_name()
        config = read_file(self.webapp.host_id, filename)
        return config

    def save_config(self):
        from apps.hosts.tasks import save_str_as_file
        # Save main config
        save_str_as_file.apply(args=[
            self.webapp.host_id,
            self.compile_config(),
            self.get_duply_config_file_name(),
            False,
        ])
        # Save excludes
        save_str_as_file.apply(args=[
            self.webapp.host_id,
            self.compile_exclude(),
            self.get_duply_config_file_name(filename='exclude'),
            False,
        ])
        # Save pre script
        save_str_as_file.apply(args=[
            self.webapp.host_id,
            self.compile_pre_script(),
            self.get_duply_config_file_name(filename='pre'),
            False,
        ])
        # Save post script
        save_str_as_file.apply(args=[
            self.webapp.host_id,
            self.compile_post_script(),
            self.get_duply_config_file_name(filename='post'),
            False,
        ])

    def init_duply_config(self):
        result = self.webapp.host.exec_cmd(
            self.get_creation_cmd())
        self.save_config()
        return result

    def compile_pre_script(self):
        import os
        from plugins.postgresql.models import (
            PostgreSQLDatabase,
            PostgreSQLUser,
        )

        config = ''
        backup_root = self.get_extra_backup_directory()

        pg_dbs = PostgreSQLDatabase.objects.filter(
            webapp=self.webapp,
        )
        for pg_db in pg_dbs:
            config += "/bin/mkdir -p {broot}/{dbname}".format(
                broot=backup_root,
                dbname=pg_db.name,
            )
            pg_user = PostgreSQLUser.objects.get(
                username=pg_db.username, pg_service=pg_db.pg_service)

            config += '''
/usr/bin/pg_dump \\"dbname={dbname} host={host} user={user} password={pwd} port={port}\\" > {dir}/db-dump.sql
'''.format(
                dbname=pg_db.name,
                host=pg_db.pg_service.host.ip_address,
                user=pg_db.username,
                pwd=pg_user.password,
                port=pg_db.pg_service.get_public_pg_port(),
                dir=os.path.join(backup_root, pg_db.name)
            )
        return config

    def compile_post_script(self):
        import os
        from plugins.postgresql.models import PostgreSQLDatabase

        config = ''
        backup_root = self.get_extra_backup_directory()

        pg_dbs = PostgreSQLDatabase.objects.filter(
            webapp=self.webapp,
        )
        for pg_db in pg_dbs:
            config += '/bin/rm -rf {dir}\n'.format(
                dir=os.path.join(backup_root, pg_db.name),
            )
        return config

    def compile_config(self):
        config = ''
        # Passphrase
        config += "GPG_PW='%s'\n" % self.passphrase

        # Target
        config += """
TARGET='{target}'
TARGET_USER='{user}'
TARGET_PASS='{password}'
""".format(target=self.target, user=self.username, password=self.password)

        # Source
        # NOTE: the real sources are described in excludes
        config += "SOURCE='/'\n"

        # Max age
        config += "MAX_AGE={0}\n".format(self.max_age)
        config += """
MAX_FULL_BACKUPS={max_full_backups}
MAX_FULLBKP_AGE={max_full_backup_age}

plugins/backups/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from apps.passwords.widgets import ShowHidePasswordWidget
from .models import BackupSettings


class BackupSettingsAdminForm(forms.ModelForm):
    password = forms.CharField(
        widget=ShowHidePasswordWidget())

    class Meta:
        model = BackupSettings
        fields = [
            'webapp', 'passphrase',
            'target',
            'username',
            'password',
            'max_age',
            'volsize',
            'max_full_backups',
            'max_full_backup_age',
            's3_european_bucket',
            's3_use_new_style',
            'duply_status',
            'schedule',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'instance' in kwargs:
            if kwargs['instance'] is not None:
                self.fields['password'].initial = kwargs['instance'].password

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.password = self.cleaned_data['password']
        if commit:
            instance.save()
        return instance


class EditBackupSettingsForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput())

    class Meta:
        model = BackupSettings
        fields = [
            'target',
            'username',
            'password',
            'max_age',
            'volsize',
            'max_full_backups',
            'max_full_backup_age',
            's3_european_bucket',
            's3_use_new_style',
            'schedule',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'instance' in kwargs:
            if kwargs['instance'] is not None:
                self.fields['password'].initial = kwargs['instance'].password
                self.fields['password'].widget = ShowHidePasswordWidget()

apps/dashboard/views.py
# coding: utf-8
from django.shortcuts import render_to_response
from django.template import RequestContext


def dashboard(request):
    return render_to_response(
        'dashboard/dashboard.html', RequestContext(request, {}))

plugins/backups/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages
from .forms import EditBackupSettingsForm

BACKUPS_ROOT = '/home/webprod/backups'


def dashboard(request, app_pk):
    from apps.applications.models import WebApplication
    app = get_object_or_404(WebApplication, pk=app_pk)

    if hasattr(app, 'backup_settings'):
        backup_settings = app.backup_settings
    else:
        backup_settings = None

    context = {
        'app': app,
        'backup_settings': backup_settings,
    }
    return render(request, 'backups/dashboard.html', context)


def configure_backups(request, app_pk):
    import os
    from apps.applications.models import WebApplication
    app = get_object_or_404(WebApplication, pk=app_pk)

    if hasattr(app, 'backup_settings'):
        form = EditBackupSettingsForm(instance=app.backup_settings)
    else:
        form = EditBackupSettingsForm()

    if request.method == 'POST':
        if hasattr(app, 'backup_settings'):
            form = EditBackupSettingsForm(
                data=request.POST,
                instance=app.backup_settings)
        else:
            form = EditBackupSettingsForm(request.POST)

        if form.is_valid():
            _bs = form.save(commit=False)
            _bs.webapp = app
            _bs.password = form.cleaned_data['password']
            _bs.save()
            return redirect(reverse('backups_index', args=(app.pk,)))

    return render(
        request, 'backups/configure.html',
        {
            'app': app,
            'form': form,
        })


def download_duply_config(request, app_pk):
    import os
    from apps.applications.models import WebApplication
    app = get_object_or_404(WebApplication, pk=app_pk)

    if hasattr(app, 'backup_settings'):
        config = app.backup_settings.get_duply_config()
        return HttpResponse(config, content_type='text/plain')
    else:
        return redirect(reverse('backups_index', args=(app.pk,)))


def rewrite_duply_config(request, app_pk):
    import os
    from apps.applications.models import WebApplication
    app = get_object_or_404(WebApplication, pk=app_pk)

    if hasattr(app, 'backup_settings'):
        config = app.backup_settings.save_config()
        return redirect(reverse('backups_index', args=(app.pk,)))
    else:
        return redirect(reverse('backups_index', args=(app.pk,)))


def start_duply_backup(request, app_pk):
    import os
    from apps.applications.models import WebApplication
    from .tasks import start_webapp_backup
    app = get_object_or_404(WebApplication, pk=app_pk)
    start_webapp_backup.delay(app.pk)
    messages.success(
        request,
        _('Task for start application backup has been started.')
    )
    return redirect(reverse('backups_index', args=(app.pk,)))

plugins/backups/templates/backups/configure.html
{% extends "applications/app_base.html" %}
{% load i18n crispy_forms_tags %}
{% load static from staticfiles %}

{% block sidebar_init %}backups{% endblock %}

{% block breadcrumbs %}
{{ block.super }}
<li><a href="{% url 'backups_index' app.pk %}">{% trans "Backups" %}</a></li>
<li class="active">{% trans "Configure backups" %}</li>
{% endblock %}

{% block content %}
<h2>{% trans "Configure backups" %}</h2>
<br>

<form role="form" method="post">
{% csrf_token %}
{{ form|crispy }}
<div class="form-group">
<button class="btn btn-primary" type="submit">
{% trans "Save" %}
</button>
<a class="btn btn-link" href="{% url 'backups_index' app.pk %}">{% trans "Cancel" %}</a>
</div>
</form>
{% endblock %}

plugins/backups/templates/backups/dashboard.html
{% extends "applications/app_base.html" %}
{% load i18n %}
{% load static from staticfiles %}

{% block sidebar_init %}backups{% endblock %}

{% block breadcrumbs %}
{{ block.super }}
<li class="active">{% trans "Backups" %}</li>
{% endblock %}

{% block content %}
<div class="btn-toolbar pull-right">
    <div class="btn-group">
    <a href="{% url 'backups_configure' app.pk %}" class="btn btn-default">
    <span class="glyphicon glyphicon-cog"></span> {% trans "Configure" %}</a>
    </div>
    {% if backup_settings %}
    <div class="btn-group">
    <a href="{% url 'backups_start' app.pk %}" class="btn btn-success">
    <span class="glyphicon glyphicon-play"></span> {% trans "Start backup" %}</a>
    </div>
    {% endif %}
</div>
<h2>{% trans "Backups" %}</h2>
<br>

{% if backup_settings %}
<div class="panel panel-default">
<div class="panel-heading">
<h3 class="panel-title">Settings</h3>
</div>
<div class="panel-body">
<table class="table table-hover">
<tr>
    <td><strong>{% trans "Target" %}</strong></td>
    <td><code>{{ backup_settings.target }}</code></td><td></td>
</tr>
<tr>
    <td><strong>{% trans "Target user / Access key" %}</strong></td>
    <td>{{ backup_settings.username }}</td><td></td>
</tr>
<tr>
    <td><strong>{% trans "Max age" %}</strong></td>
    <td>{{ backup_settings.get_max_age_display }}</td><td></td>
</tr>
<tr>
    <td><strong>{% trans "Volume size" %}</strong></td>
    <td>{{ backup_settings.volsize }} MB</td><td></td>
</tr>
<tr>
    <td><strong>{% trans "Schedule" %}</strong></td>
    <td>{{ backup_settings.get_schedule_display }}</td><td></td>
</tr>
<tr>
    <td><strong>{% trans "Duply config file" %}</strong></td>
    <td>{{ backup_settings.get_duply_config_file_name }}</td>
    <td style="text-align:right;">
        <div class="btn-group btn-group-sm">
        <a href="{% url 'backups_rewrite_config' app.pk %}" style="text-decoration:none;" class="btn btn-default">
        <span class="glyphicon glyphicon-upload"></span> {% trans "Force rewrite" %}</a>
        <a target="_blank" href="{% url 'backups_duply_config' app.pk %}" style="text-decoration:none;" class="btn btn-default">
        <span class="glyphicon glyphicon-download"></span> {% trans "Download" %}</a>
        </div>
    </td>
</tr>
</table>
</div>
</div>

{% with backup_settings.get_backup_status_as_obj as b_status %}
<div class="panel panel-default">
<div class="panel-heading">
<h3 class="panel-title">{% trans "Backup status" %}</h3>
</div>
<div class="panel-body">
<table class="table table-hover">
<tr>
    <td><strong>{% trans "Last check" %}</strong></td>
    <td>{{b_status.last_status_check.0}}</td>
</tr>
<tr>
    <td><strong>{% trans "Metadata sync status" %}</strong></td>
    <td>{{b_status.matadata_are_synchronized}}</td>
</tr>
<tr>
    <td><strong>{% trans "Last full backup" %}</strong></td>
    <td>{{b_status.last_full_backup.0}}</td>
</tr>
</table>
</div>
</div>

<div class="panel panel-default">
<div class="panel-heading">
<h3 class="panel-title">{% trans "Backup sets" %}</h3>
</div>
<div class="panel-body">
{% if b_status.backup_sets_count > 0 %}
<table class="table table-hover table-bordered table-striped">
<tr>
    <th>{% trans "Time" %}</th>
    <th>{% trans "Type of backup set" %}</th>
    <!-- <th></th> -->
</tr>
{% for s in b_status.backup_sets %}
<tr>
    <td>{{s.1}}</td>
    <td>{{s.0}}</td>
    <!-- <td></td> -->
</tr>
{% endfor %}
</table>
{% else %}
<div class="alert alert-info">
    <p>{% trans "No backup sets yet." %}</p>
</div>
{% endif %}
</div>
</div>
{% endwith %}

<div class="panel panel-info">
<div class="panel-heading">
<h3 class="panel-title">{% trans "How to restore?" %}</h3>
</div>
<div class="panel-body">
<p>{% trans "If you do not install Duply and Duplicity yet then you can use the next commands to do that:" %}</p>
<pre>
sudo add-apt-repository -y ppa:duplicity-team/ppa
sudo apt-get -qq update
sudo apt-get -y install python-pip
sudo apt-get -y install duplicity duply
sudo pip install boto
</pre>
<p>{% trans "Create a Duply site profile:" %}</p>
<pre>
{{backup_settings.get_creation_cmd}}
</pre>
<p>{% trans "Then copy downloaded conf file to the just created config folder and replace existing file." %}</p>
<hr>
<p>{% trans "Use this command for restore backup to a temporary directory:" %}</p>
<pre>
{{backup_settings.get_restore_to_dir_cmd}}
</pre>
<p>{% trans "For restore backup for specific date add it to the command like that:" %}</p>
<pre>
{{backup_settings.get_restore_to_dir_cmd}} '2013-11-08T07:38:30'
</pre>
</div>
</div>

{% comment %}
<pre>
{{backup_settings.get_backup_status_as_obj|pprint}}
</pre>
<p><code>$ {{backup_settings.get_status_cmd}}</code></p>
<pre>
{{backup_settings.duply_status}}
</pre>
{% endcomment %}


{% comment %}
<h3>pre</h3>
<pre>
{{backup_settings.compile_pre_script}}
</pre>
<h3>post</h3>
<pre>
{{backup_settings.compile_post_script}}
</pre>

<h3>conf</h3>
<pre>
{{backup_settings.compile_config}}
</pre>
<h3>exclude</h3>
<pre>
{{backup_settings.compile_exclude}}
</pre>
{% endcomment %}
{% else %}
<div class="alert alert-info">
    <p>{% trans "Backup settings are not configured." %}</p>
</div>
{% endif %}
{% endblock %}